/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vJTHEFJo4hakWdJ852JuiQ
// Component: 3MsfWbPFXJfL

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavigationBar from "../../NavigationBar"; // plasmic-import: 7H3PQrQDvA67/component
import { TabsContainer } from "@plasmicpkgs/plasmic-tabs";
import { TabButton } from "@plasmicpkgs/plasmic-tabs";
import Button from "../../Button"; // plasmic-import: lBHNzts6tFyj/component
import { TabUnderline } from "@plasmicpkgs/plasmic-tabs";
import { TabContent } from "@plasmicpkgs/plasmic-tabs";
import { AntdColumn } from "@plasmicpkgs/antd5/skinny/registerTable";
import Button2 from "../../Button"; // plasmic-import: o3RCiIr-AAAG/component
import { GraphCMSFetcher } from "@plasmicpkgs/plasmic-graphcms";
import { GraphCMSField } from "@plasmicpkgs/plasmic-graphcms";
import { RichTable } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { tableHelpers as RichTable_Helpers } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import ProjectCard from "../../ProjectCard"; // plasmic-import: Alt7_DdIrRqA/component
import ContactSection from "../../ContactSection"; // plasmic-import: N5aJkq4P8KJ9/component
import Footer from "../../Footer"; // plasmic-import: 493bmr7sdQvY/component

import { useScreenVariants as useScreenVariantscDOtgrr0S24 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: cDOtgrr0-s24/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: vJTHEFJo4hakWdJ852JuiQ/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 3MsfWbPFXJfL/css

import CheckSvgIcon from "../plasmic_tabs/icons/PlasmicIcon__CheckSvg"; // plasmic-import: zq2s7N0xWucT/icon
import IconIcon from "../plasmic_tabs/icons/PlasmicIcon__Icon"; // plasmic-import: 8K40faRNhuCj/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: fVsjnTPPUtiI/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: cAwmqPtRgCwq/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: NYIc10tcPIc3/icon
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: T-XjT_Qrw1PB/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  intro?: Flex__<"section">;
  mainTextContainer?: Flex__<"div">;
  tabsContainer?: Flex__<typeof TabsContainer>;
  tabUnderline?: Flex__<typeof TabUnderline>;
  h1?: Flex__<"h1">;
  background2?: Flex__<"div">;
  copy?: Flex__<"div">;
  hygraphFetcher?: Flex__<typeof GraphCMSFetcher>;
  hygraphField?: Flex__<typeof GraphCMSField>;
  table?: Flex__<typeof RichTable>;
  services?: Flex__<"section">;
  work?: Flex__<"section">;
  about?: Flex__<"section">;
  testimonials?: Flex__<"section">;
  contactSection?: Flex__<typeof ContactSection>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "table[].selectedRowKey",
        type: "private",
        variableType: "text",

        onMutate: generateOnMutateForSpec("selectedRowKey", RichTable_Helpers)
      },
      {
        path: "table[].selectedRow",
        type: "private",
        variableType: "object",

        onMutate: generateOnMutateForSpec("selectedRow", RichTable_Helpers)
      },
      {
        path: "table[].selectedRows",
        type: "private",
        variableType: "array",

        onMutate: generateOnMutateForSpec("selectedRows", RichTable_Helpers)
      },
      {
        path: "table[].selectedRowKeys",
        type: "private",
        variableType: "array",

        onMutate: generateOnMutateForSpec("selectedRowKeys", RichTable_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantscDOtgrr0S24()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            className={classNames("__wab_instance", sty.navigationBar)}
          />

          {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))([
            2, 3, 4
          ]).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <Stack__
                as={"section"}
                data-plasmic-name={"intro"}
                data-plasmic-override={overrides.intro}
                hasGap={true}
                className={classNames(projectcss.all, sty.intro)}
                key={currentIndex}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___9OiNt)}
                >
                  <div
                    data-plasmic-name={"mainTextContainer"}
                    data-plasmic-override={overrides.mainTextContainer}
                    className={classNames(
                      projectcss.all,
                      sty.mainTextContainer
                    )}
                  >
                    <TabsContainer
                      data-plasmic-name={"tabsContainer"}
                      data-plasmic-override={overrides.tabsContainer}
                      initialKey={"tab1"}
                    >
                      <DataCtxReader__>
                        {$ctx => (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__uEkz
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__wo0GX
                              )}
                            >
                              <TabButton
                                className={classNames(
                                  "__wab_instance",
                                  sty.tabButton__oou9O
                                )}
                                tabKey={"tab1"}
                              >
                                {(_par =>
                                  !_par
                                    ? []
                                    : Array.isArray(_par)
                                    ? _par
                                    : [_par])([2, 3, 4]).map(
                                  (__plasmic_item_1, __plasmic_idx_1) => {
                                    const currentItem = __plasmic_item_1;
                                    const currentIndex = __plasmic_idx_1;
                                    return (
                                      <Button
                                        className={classNames(
                                          "__wab_instance",
                                          sty.button___9Iv46
                                        )}
                                        key={currentIndex}
                                      >
                                        <div
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.__wab_text,
                                            sty.text__wOtG
                                          )}
                                        >
                                          {"Tab 1"}
                                        </div>
                                      </Button>
                                    );
                                  }
                                )}
                              </TabButton>
                              <TabButton
                                className={classNames(
                                  "__wab_instance",
                                  sty.tabButton__iWlDe
                                )}
                                tabKey={"tab2"}
                              >
                                <Button>
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__yMvPz
                                    )}
                                  >
                                    {"Tab 2"}
                                  </div>
                                </Button>
                              </TabButton>
                              <TabUnderline
                                data-plasmic-name={"tabUnderline"}
                                data-plasmic-override={overrides.tabUnderline}
                                className={classNames(
                                  "__wab_instance",
                                  sty.tabUnderline
                                )}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__s6Azx
                              )}
                            >
                              <TabContent
                                className={classNames(
                                  "__wab_instance",
                                  sty.tabContent__owGjh
                                )}
                                tabKey={"tab1"}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__qf1Iq
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___9IaC5
                                    )}
                                  >
                                    {"Some content for tab 1"}
                                  </div>
                                </div>
                              </TabContent>
                              <TabContent
                                className={classNames(
                                  "__wab_instance",
                                  sty.tabContent__jnVaU
                                )}
                                tabKey={"tab2"}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__ka8Zz
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__n2Jm4
                                    )}
                                  >
                                    {"Some content for tab 2"}
                                  </div>
                                </div>
                              </TabContent>
                            </div>
                          </div>
                        )}
                      </DataCtxReader__>
                    </TabsContainer>
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {"Hey there, Anna here \ud83d\udc4b"}
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vnKua
                      )}
                    >
                      {"Web designer and product designer for hire."}
                    </div>
                    <AntdColumn
                      className={classNames(
                        "__wab_instance",
                        sty.column__n2M9Z
                      )}
                      title={"Column Name"}
                    />

                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__c6AQy)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.columns__dHm6Y
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__ik5Vt
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__eZByP)}
                            displayHeight={"100%"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"none"}
                            displayMinHeight={"320px"}
                            displayMinWidth={"0"}
                            displayWidth={"100%"}
                            src={
                              "https://images.unsplash.com/photo-1530099486328-e021101a494a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2916&q=80"
                            }
                          />

                          <div
                            data-plasmic-name={"background2"}
                            data-plasmic-override={overrides.background2}
                            className={classNames(
                              projectcss.all,
                              sty.background2
                            )}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__xiIc7
                          )}
                        >
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vu1Vo
                            )}
                          >
                            <Stack__
                              as={"div"}
                              data-plasmic-name={"copy"}
                              data-plasmic-override={overrides.copy}
                              hasGap={true}
                              className={classNames(projectcss.all, sty.copy)}
                            >
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__vPFk
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__ptoyR
                                  )}
                                >
                                  {"Welcome"}
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__q5TI0
                                  )}
                                >
                                  {"Let's get going"}
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__m8Vfo
                                  )}
                                >
                                  {
                                    "Consectetur a adipiscing sagittis sed proin libero himenaeos ornare adipiscing suscipit leo vestibulum facilisi consequat nisi nisi adipiscing habitant facilisis suspendisse hac integer eget quam facilisis sem placerat fames."
                                  }
                                </div>
                              </Stack__>
                              <Stack__
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__th45J
                                )}
                              >
                                <Button2
                                  className={classNames(
                                    "__wab_instance",
                                    sty.button___07Otx
                                  )}
                                  end={
                                    <Icon4Icon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg___06GA4
                                      )}
                                      role={"img"}
                                    />
                                  }
                                  iconEnd={true}
                                  label={
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__dZtgc
                                      )}
                                    >
                                      {"Start now"}
                                    </div>
                                  }
                                  size={"large"}
                                  start={
                                    <CircleIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__hMq0N
                                      )}
                                      role={"img"}
                                    />
                                  }
                                />

                                <PlasmicLink__
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.a,
                                    projectcss.__wab_text,
                                    sty.link__mQrxp
                                  )}
                                  component={Link}
                                  href={"https://www.plasmic.app/"}
                                  platform={"nextjs"}
                                >
                                  {"Learn more..."}
                                </PlasmicLink__>
                              </Stack__>
                            </Stack__>
                          </Stack__>
                        </div>
                      </div>
                      <GraphCMSFetcher
                        data-plasmic-name={"hygraphFetcher"}
                        data-plasmic-override={overrides.hygraphFetcher}
                        className={classNames(
                          "__wab_instance",
                          sty.hygraphFetcher
                        )}
                        noAutoRepeat={false}
                        noLayout={false}
                        varOverrides={{}}
                      >
                        <DataCtxReader__>
                          {$ctx => (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__iGkWp
                              )}
                            >
                              <GraphCMSField
                                data-plasmic-name={"hygraphField"}
                                data-plasmic-override={overrides.hygraphField}
                                className={classNames(
                                  "__wab_instance",
                                  sty.hygraphField
                                )}
                                themeClassName={classNames(
                                  projectcss.root_reset,
                                  projectcss.root_reset_tags,
                                  projectcss.plasmic_default_styles,
                                  projectcss.plasmic_mixins,
                                  projectcss.plasmic_tokens,
                                  plasmic_antd_5_hostless_css.plasmic_tokens,
                                  plasmic_plasmic_rich_components_css.plasmic_tokens
                                )}
                              />
                            </div>
                          )}
                        </DataCtxReader__>
                      </GraphCMSFetcher>
                    </Stack__>
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___0ZzmH
                    )}
                    component={Link}
                    href={"#about"}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4DaoP
                      )}
                    >
                      {"About me"}
                    </div>
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__ciEph)}
                      role={"img"}
                    />
                  </PlasmicLink__>
                  {(
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? true
                      : false
                  ) ? (
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__kHKzL
                      )}
                      component={Link}
                      href={"#about"}
                      platform={"nextjs"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jJQk
                        )}
                      >
                        {"About me"}
                      </div>
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg__vuS5D)}
                        role={"img"}
                      />
                    </PlasmicLink__>
                  ) : null}
                </div>
                {(() => {
                  const child$Props = {
                    className: classNames("__wab_instance", sty.table),
                    onRowSelectionChanged: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "selectedRowKey",
                        ["table", __plasmic_idx_0, "selectedRowKey"],
                        RichTable_Helpers
                      ).apply(null, eventArgs);
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "selectedRow",
                        ["table", __plasmic_idx_0, "selectedRow"],
                        RichTable_Helpers
                      ).apply(null, eventArgs);
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "selectedRows",
                        ["table", __plasmic_idx_0, "selectedRows"],
                        RichTable_Helpers
                      ).apply(null, eventArgs);
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "selectedRowKeys",
                        ["table", __plasmic_idx_0, "selectedRowKeys"],
                        RichTable_Helpers
                      ).apply(null, eventArgs);
                    },
                    scopeClassName: sty["table__instance"],
                    selectedRowKey: generateStateValueProp($state, [
                      "table",
                      __plasmic_idx_0,
                      "selectedRowKey"
                    ]),
                    selectedRowKeys: generateStateValueProp($state, [
                      "table",
                      __plasmic_idx_0,
                      "selectedRowKeys"
                    ]),
                    themeResetClassName: classNames(
                      projectcss.root_reset,
                      projectcss.root_reset_tags,
                      projectcss.plasmic_default_styles,
                      projectcss.plasmic_mixins,
                      projectcss.plasmic_tokens,
                      plasmic_antd_5_hostless_css.plasmic_tokens,
                      plasmic_plasmic_rich_components_css.plasmic_tokens
                    )
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "selectedRowKey",
                        plasmicStateName: "table[].selectedRowKey"
                      },
                      {
                        name: "selectedRow",
                        plasmicStateName: "table[].selectedRow"
                      },
                      {
                        name: "selectedRows",
                        plasmicStateName: "table[].selectedRows"
                      },
                      {
                        name: "selectedRowKeys",
                        plasmicStateName: "table[].selectedRowKeys"
                      }
                    ],
                    [__plasmic_idx_0],
                    RichTable_Helpers ?? {},
                    child$Props
                  );
                  initializePlasmicStates(
                    $state,
                    [
                      {
                        name: "table[].selectedRowKey",
                        initFunc: ({ $props, $state, $queries }) => undefined
                      },
                      {
                        name: "table[].selectedRowKeys",
                        initFunc: ({ $props, $state, $queries }) => undefined
                      }
                    ],
                    [__plasmic_idx_0]
                  );
                  return (
                    <RichTable
                      data-plasmic-name={"table"}
                      data-plasmic-override={overrides.table}
                      {...child$Props}
                    />
                  );
                })()}
              </Stack__>
            );
          })}
          <Stack__
            as={"section"}
            data-plasmic-name={"services"}
            data-plasmic-override={overrides.services}
            hasGap={true}
            className={classNames(projectcss.all, sty.services)}
            id={"Services"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__gmZWq)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5JOj6
                )}
                id={"services"}
              >
                {"Services"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__nzDkL
                )}
              >
                {"Embracing constraints to push the boundaries."}
              </h2>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__tfn0C)}
            >
              <div className={classNames(projectcss.all, sty.column__hOqeY)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ap3JC)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/uxDesignPng.png",
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__tDne
                  )}
                >
                  {"UX/UI & Web \nDesign"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6GcX
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___3Vyld)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__dL1U5)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/brushPng.png",
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__s8RWe
                  )}
                >
                  {"Branding & visual \ndesign"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__moOae
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__ydxMl)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__yq7Up)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/programmingPng.png",
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__myMye
                  )}
                >
                  {"Web \ndevelopment"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kAynd
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"work"}
            data-plasmic-override={overrides.work}
            hasGap={true}
            className={classNames(projectcss.all, sty.work)}
            id={"work"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__uA55P)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pnDf
                )}
                id={"services"}
              >
                {"work"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__cg2Xc
                )}
              >
                {"Privileged to work with on some amazing projects."}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___7Uudr)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__rRvKg)}
              >
                <div className={classNames(projectcss.all, sty.column__vLzTa)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__gsfEe)}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__ryljI
                      )}
                      link={`/project-relaunch`}
                      title={"Project Relaunch"}
                    />
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column__gu0T4)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__fi2Cw)}
                    delay={250}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__o2Ls
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: "/plasmic/beginners_guide_website_in_3_minutes/images/abstractBackgroundJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1171,
                        aspectRatio: undefined
                      }}
                      link={`/website-redesign`}
                      title={"Website Redesign"}
                    />
                  </Reveal>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__aQsDb)}
              >
                <div className={classNames(projectcss.all, sty.column__fPr65)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__swkP)}
                    delay={500}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__pkxvf
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: "/plasmic/beginners_guide_website_in_3_minutes/images/abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                      link={`/premium-sass-design`}
                      title={"Premium Saas Design"}
                    />
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column__aJhtY)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__bUzm)}
                    delay={750}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__hwYeo
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: "/plasmic/beginners_guide_website_in_3_minutes/images/blueAndOrangeAbstractBackgroundFreeVectorJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                      link={`/web-visual-design`}
                      title={"Web Visual Graphic Design"}
                    />
                  </Reveal>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"about"}
            data-plasmic-override={overrides.about}
            hasGap={true}
            className={classNames(projectcss.all, sty.about)}
            id={"about"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__nxW)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__uaKdK
                )}
                id={"about"}
              >
                {"About Me"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___0REx)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__enN9W
                )}
              >
                {"Bridging design and no-code."}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tmSh
                )}
              >
                {
                  "Anna is an award winning, web designer specialising in no-code solutions. With over 8 years of professional experience I've helped countless startups launch & grow their business."
                }
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__rtvYw)}>
              <div className={classNames(projectcss.all, sty.freeBox___99Upl)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__c15Cc)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__meMv2)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "311px"
                        : "312px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/beginners_guide_website_in_3_minutes/images/studentGa473640711280Jpg.jpg",
                      fullWidth: 1280,
                      fullHeight: 853,
                      aspectRatio: undefined
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___8Isb)}
                    displayHeight={"312px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/beginners_guide_website_in_3_minutes/images/lukePetersB6JiNerWMz0UnsplashJpg.jpg",
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__dwAny)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kWz6I)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/benKoldeBs2Ba7T69MMUnsplashJpg.jpg",
                    fullWidth: 1920,
                    fullHeight: 2449,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__q02Bo)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__pvPkb)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/danielKorpaiAUmq852V7IUnsplashJpg.jpg",
                    fullWidth: 1920,
                    fullHeight: 2400,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___8WwI7)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___20TNp
                )}
              >
                {"TESTIMONIALS"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__i1Eq
                )}
              >
                {"Hear from the folks I've worked with."}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__maexk)}>
              <div className={classNames(projectcss.all, sty.freeBox__id4Lw)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__koxOg)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ol1H)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9VjqU
                      )}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__q3YZv)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___8YnQ)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__cac5S)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__pxo2U)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__xk8Cg)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___5SQfA
                      )}
                    >
                      {"Very experienced"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lpJgb
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__ur1T)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___13Ggo
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__szSpz)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/beginners_guide_website_in_3_minutes/images/alexSuprunZHvM3XioHoEUnsplashJpg.jpg",
                            fullWidth: 640,
                            fullHeight: 640,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__wlKyW
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___1KjXp
                          )}
                        >
                          {"Albert David"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___66W6I
                          )}
                        >
                          {"Marketing Manager, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__bSwz2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jsMyG)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__wAkzQ)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__xmgfx)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___97S5U)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__tCnzB)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__gBnuT)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__dE61V
                      )}
                    >
                      {"Very fast & skillful"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___72IZh
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__smz8C)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__mvqBf
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__fYDit)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/beginners_guide_website_in_3_minutes/images/christopherCampbellRDeoVtE7VOsUnsplashJpg.jpg",
                            fullWidth: 640,
                            fullHeight: 427,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dUqdD
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___77Oxb
                          )}
                        >
                          {"Arolina"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zYXna
                          )}
                        >
                          {"Manager, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__loFzM)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__uWOru)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__sftEa)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__o0Oa)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___2Iqzl)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__gY8X)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__tZjk5)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__i0BMu)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__adeJj)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___6QxOe
                      )}
                    >
                      {"skilled communicator"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qkYTr
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns___9Yi2)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__y6WP)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__u81M)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/beginners_guide_website_in_3_minutes/images/courtneyCookTsZo17R3M0SUnsplashJpg.jpg",
                            fullWidth: 640,
                            fullHeight: 960,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__vdVy2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__agg5K
                          )}
                        >
                          {"Firmona"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ja0YF
                          )}
                        >
                          {"Founder, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__xVuhJ)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mJXfB)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__hNP)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__pgXoU)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__nhhF8)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___6WdDg)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__yPxa1)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__smvpr
                      )}
                    >
                      {"Great design skills"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__czu1D
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__xJmEx)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__epYoS
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__h1UWk)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/beginners_guide_website_in_3_minutes/images/alexanderHippIEebWgY6LAUnsplashJpg.jpg",
                            fullWidth: 640,
                            fullHeight: 640,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(projectcss.all, sty.column__yoDx)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9ADqe
                          )}
                        >
                          {"Motherson"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fKM9
                          )}
                        >
                          {"Design Lead, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </Stack__>
          <ContactSection
            data-plasmic-name={"contactSection"}
            data-plasmic-override={overrides.contactSection}
            className={classNames("__wab_instance", sty.contactSection)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigationBar",
    "intro",
    "mainTextContainer",
    "tabsContainer",
    "tabUnderline",
    "h1",
    "background2",
    "copy",
    "hygraphFetcher",
    "hygraphField",
    "table",
    "services",
    "work",
    "about",
    "testimonials",
    "contactSection",
    "footer"
  ],
  navigationBar: ["navigationBar"],
  intro: [
    "intro",
    "mainTextContainer",
    "tabsContainer",
    "tabUnderline",
    "h1",
    "background2",
    "copy",
    "hygraphFetcher",
    "hygraphField",
    "table"
  ],
  mainTextContainer: [
    "mainTextContainer",
    "tabsContainer",
    "tabUnderline",
    "h1",
    "background2",
    "copy",
    "hygraphFetcher",
    "hygraphField"
  ],
  tabsContainer: ["tabsContainer", "tabUnderline"],
  tabUnderline: ["tabUnderline"],
  h1: ["h1"],
  background2: ["background2"],
  copy: ["copy"],
  hygraphFetcher: ["hygraphFetcher", "hygraphField"],
  hygraphField: ["hygraphField"],
  table: ["table"],
  services: ["services"],
  work: ["work"],
  about: ["about"],
  testimonials: ["testimonials"],
  contactSection: ["contactSection"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navigationBar: typeof NavigationBar;
  intro: "section";
  mainTextContainer: "div";
  tabsContainer: typeof TabsContainer;
  tabUnderline: typeof TabUnderline;
  h1: "h1";
  background2: "div";
  copy: "div";
  hygraphFetcher: typeof GraphCMSFetcher;
  hygraphField: typeof GraphCMSField;
  table: typeof RichTable;
  services: "section";
  work: "section";
  about: "section";
  testimonials: "section";
  contactSection: typeof ContactSection;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    intro: makeNodeComponent("intro"),
    mainTextContainer: makeNodeComponent("mainTextContainer"),
    tabsContainer: makeNodeComponent("tabsContainer"),
    tabUnderline: makeNodeComponent("tabUnderline"),
    h1: makeNodeComponent("h1"),
    background2: makeNodeComponent("background2"),
    copy: makeNodeComponent("copy"),
    hygraphFetcher: makeNodeComponent("hygraphFetcher"),
    hygraphField: makeNodeComponent("hygraphField"),
    table: makeNodeComponent("table"),
    services: makeNodeComponent("services"),
    work: makeNodeComponent("work"),
    about: makeNodeComponent("about"),
    testimonials: makeNodeComponent("testimonials"),
    contactSection: makeNodeComponent("contactSection"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Anna.Design",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
